langauge: c
dist: xenial
services:
  - xvfb
env:
  global:
    - RACKET_DIR=~/racket
    - RACKET_MINIMAL=1
  matrix:
    - RACKET_VERSION=HEADCS
    - RACKET_VERSION=HEAD
matrix:
  fast_finish: true

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - raco pkg install --fail-fast -D --deps search-auto https://github.com/florence/pict.git?path=pict-lib#diss
  - raco pkg install --fail-fast -D --deps search-auto https://github.com/florence/circuitous.git?path=circuitous-lib
  - xvfb-run -a raco pkg install -j 1 --fail-fast -D --deps search-auto

script:
 - make TRAVIS="travis_wait 60"

