langauge: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=HEADCS
    - RACKET_VERSION=HEAD
matrix:
  fast_finish: true

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - raco pkg install https://github.com/florence/pict.git?path=pict-lib#diss
  - raco pkg install https://github.com/florence/circuitous.git?path=circuitous-lib

script:
 - make

