name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    
    env: 
      RACKET_VERSION: HEAD
      RACKET_MINIMAL: 1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

 
    - name: setup racket
      run: |
        export RACKET_DIR=$HOME/racket 
        export RACKET_BIN=$HOME/racket/bin
        git clone https://github.com/greghendershott/travis-racket.git ../install-racket
        cat ../install-racket/install-racket.sh | bash
        
    - name: setup xvfb
      run: |
        sudo apt-get install xvfb graphviz
        
    - name: install racket
      run: |
        export RACKET_DIR=$HOME/racket 
        export RACKET_BIN=$HOME/racket/bin
        ${RACKET_BIN}/raco pkg install --fail-fast -D --deps search-auto https://github.com/florence/pict.git?path=pict-lib#diss
        ${RACKET_BIN}/raco pkg install --fail-fast -D --deps search-auto https://github.com/florence/circuitous.git?path=circuitous-lib
        xvfb-run -a ${RACKET_BIN}/raco pkg install -j 1 --fail-fast -D --deps search-auto
        
    - name: test
      run: |
        export RACKET_DIR=$HOME/racket 
        export RACKET_BIN=$HOME/racket/bin
        xvfb-run -a make RACO_PATH=${RACKET_BIN}/

    - name: Cleanup xvfb pidx
      uses: bcomnes/cleanup-xvfb@v1

